name: Deploy Powerhouse Router
on:
    push:
        branches: [main]
jobs:
    build:
        environment: Production
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build, Push and Release Router to Heroku.
              uses: gonuit/heroku-docker-deploy@v1.3.3
              with:
                  email: ${{ secrets.HEROKU_EMAIL }}
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_ROUTER_NAME }}
                  process_type: web
